import devRun from '../../share/dev';
import { getSuffix, getType, getUUID } from '../lib/FileProcessor';
console.info('here is /back/index.ts');
devRun();
console.info(getUUID());
console.info(getSuffix('/root/home/wwwnode/a.doc'));
console.info(getSuffix('/root/home/wwwno.de/a.doc'));
console.info(getSuffix('/root/home/wwwno.de/c'));
console.info(getSuffix('/root/home/wwwno.de/adoc.aaaaaa'));
console.info(getType('pdf'));
// console.info(parsePath('/root/home/wwwno.de/adoc.aaaaaa'));
