import {NodeItem} from '@/struct';

const demos = [
  //--- folder ---
  {
    id: 1,
    title: 'this is title',
    description: 'cover',
    type: 'folder',
    cover: {
      id: 1,
      path_preview: '/smp/1680X720.jpg',
      path_normal: '/smp/1680X720.jpg',
      path_raw: '',
    },
    is_file: 0,
    is_fav: 1,
    status: 1,
    time_create: '1919-08-10 11:45:14',
    time_update: '1919-08-10 11:45:14',
    tree: {
      id: [0, 1, 2, 3, 4,],
      title: ['root', 'path1', 'path2', 'path3', 'path4',],
    },
  },
  {
    id: 2,
    title: 'this is title',
    description: 'no cover',
    type: 'folder',
    is_file: 0,
    is_fav: 0,
    status: 1,
    time_create: '1919-08-10 11:45:14',
    time_update: '1919-08-10 11:45:14',
    tree: {
      id: [0, 1, 2, 3, 4,],
      title: ['root', 'path1', 'path2', 'path3', 'path4',],
    },
  },
  {
    id: 3,
    title: 'this is title',
    description: 'no cover, tag',
    type: 'folder',
    is_file: 0,
    is_fav: 0,
    status: 1,
    time_create: '1919-08-10 11:45:14',
    time_update: '1919-08-10 11:45:14',
    tree: {
      id: [0, 1, 2, 3, 4,],
      title: ['root', 'path1', 'path2', 'path3', 'path4',],
    },
    tag: [
      {
        id: 1, title: 'language',
        sub: [
          {id: 1, title: 'chinese',},
        ],
      },
      {
        id: 2, title: 'parody',
        sub: [
          {id: 2, title: 'genshin impact',},
        ],
      },
      {
        id: 3, title: 'female',
        sub: [
          {id: 3, title: 'horn',},
          {id: 4, title: 'bikini',},
          {id: 5, title: 'gloves',},
          {id: 6, title: 'long hair',},
          {id: 7, title: 'blue hair',},
          {id: 8, title: 'swim suit',},
        ],
      },
      {
        id: 4, title: 'misc',
        sub: [
          {id: 9, title: 'artist cg',},
          {id: 10, title: 'slime',},
          {id: 10, title: 'slime',},
        ],
      },
    ],
  },
  //--- image ---
  {
    id: 4,
    title: 'img s:720X960 title',
    description: 'cover',
    type: 'image',
    cover: {
      id: 1,
      path_preview: '/smp/720X960.jpg',
      path_normal: '/smp/720X960.jpg',
      path_raw: '/smp/720X960.jpg',
    },
    is_file: 1,
    is_fav: 1,
    time_create: '1919-08-10 11:45:14',
    time_update: '1919-08-10 11:45:14',
    file: {
      id: 1,
      path_preview: '/smp/720X960.jpg',
      path_normal: '/smp/720X960.jpg',
      path_raw: '/smp/720X960.jpg',
    },
    tree: {
      id: [0, 1, 2, 3, 4,],
      title: ['root', 'path1', 'path2', 'path3', 'path4',],
    },
  },
  {
    id: 5,
    title: 'img s:960X720 title',
    description: 'no cover',
    type: 'image',
    cover: {
      id: 1,
      path_preview: '/smp/960X720.jpg',
      path_normal: '/smp/960X720.jpg',
      path_raw: '/smp/960X720.jpg',
    },
    is_file: 1,
    is_fav: 1,
    time_create: '1919-08-10 11:45:14',
    time_update: '1919-08-10 11:45:14',
    file: {
      id: 1,
      path_preview: '/smp/960X720.jpg',
      path_normal: '/smp/960X720.jpg',
      path_raw: '/smp/960X720.jpg',
    },
    tree: {
      id: [0, 1, 2, 3, 4,],
      title: ['root', 'path1', 'path2', 'path3', 'path4',],
    },
  },
  {
    id: 6,
    title: 'img s:1680X720 title',
    description: 'no cover, tag',
    type: 'image',
    cover: {
      id: 1,
      path_preview: '/smp/1680X720.jpg',
      path_normal: '/smp/1680X720.jpg',
      path_raw: '/smp/1680X720.jpg',
    },
    is_file: 1,
    is_fav: 1,
    time_create: '1919-08-10 11:45:14',
    time_update: '1919-08-10 11:45:14',
    file: {
      id: 1,
      path_preview: '/smp/1680X720.jpg',
      path_normal: '/smp/1680X720.jpg',
      path_raw: '/smp/1680X720.jpg',
    },
    tree: {
      id: [0, 1, 2, 3, 4,],
      title: ['root', 'path1', 'path2', 'path3', 'path4',],
    },
    tag: [
      {
        id: 1, title: 'language',
        sub: [
          {id: 1, title: 'chinese',},
        ],
      },
      {
        id: 2, title: 'parody',
        sub: [
          {id: 2, title: 'genshin impact',},
        ],
      },
      {
        id: 3, title: 'female',
        sub: [
          {id: 3, title: 'horn',},
          {id: 4, title: 'bikini',},
          {id: 5, title: 'gloves',},
          {id: 6, title: 'long hair',},
          {id: 7, title: 'blue hair',},
          {id: 8, title: 'swim suit',},
        ],
      },
      {
        id: 4, title: 'misc',
        sub: [
          {id: 9, title: 'artist cg',},
          {id: 10, title: 'slime',},
          {id: 10, title: 'slime',},
        ],
      },
    ],
  },
  //--- audio ---
  {
    id: 7,
    title: 'audio:asa.mp3 title',
    description: 'cover, file preview',
    type: 'audio',
    cover: {
      id: 1,
      path_preview: '/smp/asa.jpg',
      // path_preview: '/smp/asa.jpg',
      path_normal: '/smp/asa.mp3',
      path_raw: '/smp/asa.mp3',
    },
    is_file: 1,
    is_fav: 1,
    time_create: '1919-08-10 11:45:14',
    time_update: '1919-08-10 11:45:14',
    file: {
      id: 1,
      path_preview: '/smp/asa.jpg',
      // path_preview: '/smp/asa.jpg',
      path_normal: '/smp/asa.mp3',
      path_raw: '/smp/asa.mp3',
    },
    tree: {
      id: [0, 1, 2, 3, 4,],
      title: ['root', 'path1', 'path2', 'path3', 'path4',],
    },
  },
  {
    id: 8,
    title: 'audio:butterfly.mp3 title',
    description: 'no cover, file preview',
    type: 'audio',
    is_file: 1,
    is_fav: 1,
    time_create: '1919-08-10 11:45:14',
    time_update: '1919-08-10 11:45:14',
    file: {
      id: 1,
      path_preview: '/smp/butterfly.jpg',
      // path_preview: '/smp/butterfly.jpg',
      path_normal: '/smp/butterfly.mp3',
      path_raw: '/smp/butterfly.mp3',
    },
    tree: {
      id: [0, 1, 2, 3, 4,],
      title: ['root', 'path1', 'path2', 'path3', 'path4',],
    },
  },
  {
    id: 9,
    title: 'audio:katyusha.mp3 title',
    description: 'no cover, no file preview',
    type: 'audio',
    is_file: 1,
    is_fav: 1,
    time_create: '1919-08-10 11:45:14',
    time_update: '1919-08-10 11:45:14',
    file: {
      id: 1,
      path_preview: '',
      path_normal: '/smp/katyusha.mp3',
      path_raw: '/smp/katyusha.mp3',
    },
    tree: {
      id: [0, 1, 2, 3, 4,],
      title: ['root', 'path1', 'path2', 'path3', 'path4',],
    },
    tag: [
      {
        id: 1, title: 'language',
        sub: [
          {id: 1, title: 'chinese',},
        ],
      },
      {
        id: 2, title: 'parody',
        sub: [
          {id: 2, title: 'genshin impact',},
        ],
      },
      {
        id: 3, title: 'female',
        sub: [
          {id: 3, title: 'horn',},
          {id: 4, title: 'bikini',},
          {id: 5, title: 'gloves',},
          {id: 6, title: 'long hair',},
          {id: 7, title: 'blue hair',},
          {id: 8, title: 'swim suit',},
        ],
      },
      {
        id: 4, title: 'misc',
        sub: [
          {id: 9, title: 'artist cg',},
          {id: 10, title: 'slime',},
          {id: 10, title: 'slime',},
        ],
      },
    ],
  },
  //--- video ---
  {
    id: 10,
    title: 'video:madoka.mp4 title',
    description: 'cover, file preview',
    type: 'video',
    cover: {
      id: 1,
      path_preview: '/smp/madoka.jpg',
      // path_preview: '/smp/madoka.jpg',
      path_subtitle: '/smp/madoka.vtt',
      path_normal: '/smp/madoka.mp4',
      path_raw: '/smp/madoka.mp4',
    },
    is_file: 1,
    is_fav: 1,
    time_create: '1919-08-10 11:45:14',
    time_update: '1919-08-10 11:45:14',
    file: {
      id: 1,
      path_preview: '/smp/madoka.jpg',
      // path_preview: '/smp/madoka.jpg',
      path_subtitle: '/smp/madoka.vtt',
      path_normal: '/smp/madoka.mp4',
      path_raw: '/smp/madoka.mp4',
    },
    tree: {
      id: [0, 1, 2, 3, 4,],
      title: ['root', 'path1', 'path2', 'path3', 'path4',],
    },
  },
  {
    id: 11,
    title: 'video:rail.mp4 title',
    description: 'no cover, file preview',
    type: 'video',
    is_file: 1,
    is_fav: 1,
    time_create: '1919-08-10 11:45:14',
    time_update: '1919-08-10 11:45:14',
    file: {
      id: 1,
      path_preview: '/smp/rail.jpg',
      // path_preview: '/smp/rail.jpg',
      // path_subtitle: '/smp/rail.vtt',
      path_normal: '/smp/rail.mp4',
      path_raw: '/smp/rail.mp4',
    },
    tree: {
      id: [0, 1, 2, 3, 4,],
      title: ['root', 'path1', 'path2', 'path3', 'path4',],
    },
  },
  {
    id: 12,
    title: 'video:shinobu.mp4 title',
    description: 'no cover, no file preview',
    type: 'video',
    is_file: 1,
    is_fav: 1,
    time_create: '1919-08-10 11:45:14',
    time_update: '1919-08-10 11:45:14',
    file: {
      id: 1,
      path_preview: '',
      // path_preview: '/smp/shinobu.jpg',
      // path_subtitle: '/smp/shinobu.vtt',
      path_normal: '/smp/shinobu.mp4',
      path_raw: '/smp/shinobu.mp4',
    },
    tree: {
      id: [0, 1, 2, 3, 4,],
      title: ['root', 'path1', 'path2', 'path3', 'path4',],
    },
    tag: [
      {
        id: 1, title: 'language',
        sub: [
          {id: 1, title: 'chinese',},
        ],
      },
      {
        id: 2, title: 'parody',
        sub: [
          {id: 2, title: 'genshin impact',},
        ],
      },
      {
        id: 3, title: 'female',
        sub: [
          {id: 3, title: 'horn',},
          {id: 4, title: 'bikini',},
          {id: 5, title: 'gloves',},
          {id: 6, title: 'long hair',},
          {id: 7, title: 'blue hair',},
          {id: 8, title: 'swim suit',},
        ],
      },
      {
        id: 4, title: 'misc',
        sub: [
          {id: 9, title: 'artist cg',},
          {id: 10, title: 'slime',},
          {id: 10, title: 'slime',},
        ],
      },
    ],
  },
  //--- binary ---
  {
    id: 13,
    title: 'binary:zzz title',
    description: 'description',
    type: 'binary',
    is_file: 1,
    is_fav: 1,
    time_create: '1919-08-10 11:45:14',
    time_update: '1919-08-10 11:45:14',
    file: {
      id: 1,
      path_preview: '',
      path_normal: '',
      path_raw: '',
    },
    tree: {
      id: [0, 1, 2, 3, 4,],
      title: ['root', 'path1', 'path2', 'path3', 'path4',],
    },
  },
  {
    id: 14,
    title: 'binary:zzz title',
    description: 'description',
    type: 'binary',
    is_file: 1,
    is_fav: 1,
    time_create: '1919-08-10 11:45:14',
    time_update: '1919-08-10 11:45:14',
    file: {
      id: 1,
      path_preview: '',
      path_normal: '',
      path_raw: '',
    },
    tree: {
      id: [0, 1, 2, 3, 4,],
      title: ['root', 'path1', 'path2', 'path3', 'path4',],
    },
  },
  {
    id: 15,
    title: 'binary:zzz title',
    description: 'description',
    type: 'binary',
    is_file: 1,
    is_fav: 1,
    time_create: '1919-08-10 11:45:14',
    time_update: '1919-08-10 11:45:14',
    file: {
      id: 1,
      path_preview: '',
      path_normal: '',
      path_raw: '',
    },
    tree: {
      id: [0, 1, 2, 3, 4,],
      title: ['root', 'path1', 'path2', 'path3', 'path4',],
    },
  },
  //--- archive ---
  {
    id: 16,
    title: 'archive:zzz title',
    description: 'description',
    type: 'archive',
    is_file: 1,
    is_fav: 1,
    time_create: '1919-08-10 11:45:14',
    time_update: '1919-08-10 11:45:14',
    file: {
      id: 1,
      path_preview: '',
      path_normal: '',
      path_raw: '',
    },
    tree: {
      id: [0, 1, 2, 3, 4,],
      title: ['root', 'path1', 'path2', 'path3', 'path4',],
    },
  },
  {
    id: 17,
    title: 'archive:zzz title',
    description: 'description',
    type: 'archive',
    is_file: 1,
    is_fav: 1,
    time_create: '1919-08-10 11:45:14',
    time_update: '1919-08-10 11:45:14',
    file: {
      id: 1,
      path_preview: '',
      path_normal: '',
      path_raw: '',
    },
    tree: {
      id: [0, 1, 2, 3, 4,],
      title: ['root', 'path1', 'path2', 'path3', 'path4',],
    },
  },
  {
    id: 18,
    title: 'archive:zzz title',
    description: 'description',
    type: 'archive',
    is_file: 1,
    is_fav: 1,
    time_create: '1919-08-10 11:45:14',
    time_update: '1919-08-10 11:45:14',
    file: {
      id: 1,
      path_preview: '',
      path_normal: '',
      path_raw: '',
    },
    tree: {
      id: [0, 1, 2, 3, 4,],
      title: ['root', 'path1', 'path2', 'path3', 'path4',],
    },
  },
  //--- text ---
  {
    id: 19,
    title: 'text:19zzz title',
    description: 'description',
    type: 'text',
    is_file: 1,
    is_fav: 1,
    time_create: '1919-08-10 11:45:14',
    time_update: '1919-08-10 11:45:14',
    file: {
      id: 1,
      path_preview: '',
      path_normal: '',
      path_raw: '',
    },
    tree: {
      id: [0, 1, 2, 3, 4,],
      title: ['root', 'path1', 'path2', 'path3', 'path4',],
    },
  },
  {
    id: 20,
    title: 'text:20zzz title',
    description: 'description',
    type: 'text',
    is_file: 1,
    is_fav: 1,
    time_create: '1919-08-10 11:45:14',
    time_update: '1919-08-10 11:45:14',
    file: {
      id: 1,
      path_preview: '',
      path_normal: '',
      path_raw: '',
    },
    tree: {
      id: [0, 1, 2, 3, 4,],
      title: ['root', 'path1', 'path2', 'path3', 'path4',],
    },
  },
  {
    id: 21,
    title: 'text:21zzz title',
    description: 'description',
    type: 'text',
    is_file: 1,
    is_fav: 1,
    time_create: '1919-08-10 11:45:14',
    time_update: '1919-08-10 11:45:14',
    file: {
      id: 1,
      path_preview: '',
      path_normal: '',
      path_raw: '',
    },
    tree: {
      id: [0, 1, 2, 3, 4,],
      title: ['root', 'path1', 'path2', 'path3', 'path4',],
    },
  },
] as Array<NodeItem>;

export default demos;
