#目前用于一些bash脚本的转义字符
#注意FileProcessor的get方法和watcher也依赖windows的分隔符，且get没有做兼容
windows = false
checksum = ['xxh128sum', 'b3sum']
import_ignore = ["thumbs.db", "_macosx", "desktop.ini", ".ds_store", "_tags.json", ".sync", ".git", ".idea", ".vscode"]
#为true则会打印报错信息
public = true

[port]
api = 8090
webdav = 8095

#[auth.local]
#name = "root"
#password = "root"

[db]
#driver= 'mysql'
#host= '127.0.0.1'
#port= 3306
#database= 'toshokan2'
#account= 'root'
#password= 'root'
driver = 'postgresql'
host = '{{pg_host}}'
port = '{{pg_port}}'
account = '{{pg_account}}'
password = '{{pg_password}}'
database = '{{pg_database}}'

[suffix]
video = ['mp4', 'avi', 'mkv', 'm4a', '3gp', 'flv', 'hlv', 'rm', 'rmvb']
audio = ['wav', 'flac', 'mp3', 'aac']
image = ['jpg', 'png', 'jpeg', 'tif', 'tiff', 'bmp', 'gif', 'webp']
text = ['txt', 'html', 'json', 'sql', 'csv', 'htm', 'conf', 'md', 'log']
subtitle = ['vtt', 'ass', 'ssa', 'sub', 'srt', 'pjs']
pdf = ['pdf']
office = ['doc', 'docm', 'docx', 'dot', 'dotm', 'dotx', 'epub', 'odt', 'ott', 'rtf', 'wps', 'wpt', 'csv', 'et', 'ett', 'xls', 'xlsb', 'xlsm', 'xlsx', 'xlt', 'xltm', 'xltx', 'dps', 'dpt', 'pot', 'potm', 'potx', 'pps', 'ppsm', 'ppsx', 'ppt', 'pptm', 'pptx']

[path]
root = '/myNas/file'
root_web = '/file'
api = '/api'
webdav = '/webdav'
prefix_temp = '__t'
prefix_preview = '_'
prefix_normal = '__'
prefix_cover = '___'

[parser]
ffProgram = 'ffmpeg -v quiet -hide_banner'

[parser.cover]
format = 'webp'
max_length = 320
allow_size = 131072
allow_container = ['jpg', 'jpeg', 'image2', 'png', 'gif', 'webp', ]
ff_encoder = '-c:v webp -quality 65'

[parser.preview]
format = 'webp'
max_length = 1280
allow_size = 524288
allow_container = ['jpg', 'jpeg', 'image2', 'png', 'gif', 'webp', ]
ff_encoder = '-c:v webp -quality 75'

[parser.image]
format = 'webp'
max_length = 2560
allow_size = 2097152
allow_container = ['jpg', 'jpeg', 'image2', 'png', 'gif', 'webp']
ff_encoder = '-c:v webp -quality 80'

[parser.video]
length = 1920
length_small = 1280
format = 'mp4'
allow_codec = ['vp8', 'vp9', 'h264', 'hevc', 'av1', 'vp10', ]
allow_rate = 917504
allow_container = ['mp4', 'ogg', 'webm', 'm4a', ]
#nvenc
#ff_encoder = '-c:v av1_nvenc -profile:v main10 -preset slow -tune hq -cq 22 -bf 3 -pix_fmt p010le -multipass qres -rc-lookahead 32'
#ff_encoder = '-c:v hevc_nvenc -profile:v main10 -preset slow -tune hq -qp 20 -bf 3 -pix_fmt p010le -multipass qres -rc-lookahead 32'
#quicksync
#ff_encoder = '-c:v av1_qsv -profile:v main -preset slow -q:v 27 -bf 3 -pix_fmt p010le'
#cpu
ff_encoder = '-c:v libx265 -crf 15 -bf 3 -pix_fmt yuv420p10le'

[parser.audio]
format = 'aac'
codec_lib = 'aac'
allow_codec = ['flac', 'mp3', 'aac', 'wav', 'vorbis', 'ogg', 'opus', ]
allow_container = ['flac', 'mp3', 'aac', 'wav', 'vorbis', 'ogg', ]
allow_rate = 131072
priority_kw = ['jpn', 'jps', 'japan', 'jp', '日', 'cht', 'chs', 'chin', 'zh-', '中', 'us', 'en', '英', ]
ff_encoder = '-c:a aac -q:a 1.3'

[parser.subtitle]
format = 'vtt'
allow_container = ['webvtt', ]
allow_codec = ['ass', 'ssa', 'vtt', 'srt', 'subrip', 'mov_text', 'webvtt', ]
priority_kw = ['cht', 'chs', 'chin', 'zh-', '中', 'jpn', 'jps', 'japan', 'jp', '日', 'us', 'en', '英', ]

[web]
#origin = 'http://172.17.0.1:85'
onlyoffice_enabled = '{{onlyoffice_enabled}}'
#onlyoffice_enabled = 'true'
# 写进env了，没有用
onlyoffice_origin = '{{onlyoffice_origin}}'
onlyoffice_jwt_secret = '{{onlyoffice_jwt_secret}}'
link_nav = [['Hyper', ''], ['Router', ''], ['Spider', ''], ['Git', ''], ['Torrent', '']]


































