name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: |
        docker build -t 0xee/my_nas:${{ github.sha }} .
        docker tag 0xee/my_nas:${{ github.sha }} 0xee/my_nas:latest
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push Docker image to Docker Hub
      run: |
        docker push 0xee/my_nas:latest
        docker push 0xee/my_nas:$(date +%s)
